### ISSUE TITLE
Update the qulice

### ISSUE THREAD

**Issue by l3r8yJ** [l3r8yJ/oop-cop#160]

**Comment by zoeself** [comment]
@l3r8yJ thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by l3r8yJ** [comment]
@l3r8yJ the issue body is empty, please provide more details for this problem.

**Comment by zoeself** [comment]
@l3r8yJ I couldn't find any assignee for this task. This is either because there are no contributors with role ``DEV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.
