### ISSUE TITLE
Let's print actual class name length

### ISSUE THREAD

**Issue by h1alexbel** [l3r8yJ/oop-cop#175]
I got this error:

```text
'DeepInfraRequest' has bad naming, class name is more than 15, consider more simple name
[ERROR] 	read: 'https://www.yegor256.com/2015/01/12/compound-name-is-code-smell.html' (LongClassNameCheck)
```

This error only states that 'DeepInfraRequest' class name length is more than `15` chars, but does not print what is the actual length of this class. It can improve developer experience with oop-cop error handling

**Comment by h1alexbel** [comment]
@l3r8yJ WDYT?

**Comment by l3r8yJ** [comment]
@h1alexbel thanks for the report, but here some unclear moments:
    
    
* It's not clear what is the actual length of the class name (Bug report does not provide the actual length). Consider adding the actual length of the class name to the error message.
    
Generated with `Phind/Phind-CodeLlama-34B-v2`

**Comment by l3r8yJ** [comment]
@h1alexbel good suggestion

**Comment by zoeself** [comment]
@l3r8yJ I couldn't find any assignee for this task. This is either because there are no contributors with role ``DEV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by l3r8yJ** [comment]
@rultor release, tag is `0.2.9`
